/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type SanityFileAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
}

export type Footer = {
  _id: string
  _type: 'footer'
  _createdAt: string
  _updatedAt: string
  _rev: string
  items?: Array<{
    document: {
      asset: SanityFileAssetReference
      media?: unknown
      _type: 'file'
    }
    title: string
    _key: string
  }>
  info?: InternationalizedArraySimpleBlockContent
  contacts?: InternationalizedArraySimpleBlockContent
}

export type InternationalizedArraySimpleBlockContent = Array<
  {
    _key: string
  } & InternationalizedArraySimpleBlockContentValue
>

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type FieldReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'field'
}

export type ProjectReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'project'
}

export type Homepage = {
  _id: string
  _type: 'homepage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  stickers: Array<{
    asset: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
    _key: string
  }>
  aboutUs: InternationalizedArrayBlockContentWithHeadings
  fields: Array<
    {
      _key: string
    } & FieldReference
  >
  projects?: Array<
    {
      _key: string
    } & ProjectReference
  >
  references?: Array<
    {
      _key: string
    } & ProjectReference
  >
}

export type InternationalizedArrayBlockContentWithHeadings = Array<
  {
    _key: string
  } & InternationalizedArrayBlockContentWithHeadingsValue
>

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type Project = {
  _id: string
  _type: 'project'
  _createdAt: string
  _updatedAt: string
  _rev: string
  active?: boolean
  title?: InternationalizedArrayString
  date?: string
  fields?: Array<
    {
      _key: string
    } & FieldReference
  >
  cover?: ImageObject
  web?: InternationalizedArrayLinkText
  location?: InternationalizedArrayLinkText
  youtube?: string
  subtitle?: InternationalizedArraySimpleBlockContent
  description: InternationalizedArraySimpleBlockContent
  gallery?: Array<
    {
      _key: string
    } & ImageObject
  >
}

export type InternationalizedArrayLinkText = Array<
  {
    _key: string
  } & InternationalizedArrayLinkTextValue
>

export type ImageObject = {
  _type: 'imageObject'
  asset: SanityImageAssetReference
  media?: unknown
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  altTextSk?: string
  altTextEn?: string
  author?: string
}

export type InternationalizedArrayString = Array<
  {
    _key: string
  } & InternationalizedArrayStringValue
>

export type Field = {
  _id: string
  _type: 'field'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: InternationalizedArrayString
  icon: {
    asset: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  body: InternationalizedArraySimpleBlockContent
}

export type LinkText = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal'
  listItem?: never
  markDefs?: Array<{
    href?: string
    _type: 'link'
    _key: string
  }>
  level?: number
  _type: 'block'
  _key: string
}>

export type WebInput = {
  _type: 'webInput'
  title?: InternationalizedArrayString
  url?: string
}

export type BlockContentWithHeadings = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal' | 'h2'
  listItem?: 'bullet'
  markDefs?: Array<{
    href?: string
    _type: 'link'
    _key: string
  }>
  level?: number
  _type: 'block'
  _key: string
}>

export type SimpleBlockContent = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal'
  listItem?: never
  markDefs?: Array<{
    href?: string
    _type: 'link'
    _key: string
  }>
  level?: number
  _type: 'block'
  _key: string
}>

export type InternationalizedArrayLinkTextValue = {
  _type: 'internationalizedArrayLinkTextValue'
  value?: LinkText
  language: string
}

export type InternationalizedArrayBlockContentWithHeadingsValue = {
  _type: 'internationalizedArrayBlockContentWithHeadingsValue'
  value?: BlockContentWithHeadings
  language: string
}

export type InternationalizedArraySimpleBlockContentValue = {
  _type: 'internationalizedArraySimpleBlockContentValue'
  value?: SimpleBlockContent
  language: string
}

export type InternationalizedArrayStringValue = {
  _type: 'internationalizedArrayStringValue'
  value?: string
  language: string
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type AllSanitySchemaTypes =
  | SanityFileAssetReference
  | Footer
  | InternationalizedArraySimpleBlockContent
  | SanityImageAssetReference
  | FieldReference
  | ProjectReference
  | Homepage
  | InternationalizedArrayBlockContentWithHeadings
  | SanityImageCrop
  | SanityImageHotspot
  | Project
  | InternationalizedArrayLinkText
  | ImageObject
  | InternationalizedArrayString
  | Field
  | LinkText
  | WebInput
  | BlockContentWithHeadings
  | SimpleBlockContent
  | InternationalizedArrayLinkTextValue
  | InternationalizedArrayBlockContentWithHeadingsValue
  | InternationalizedArraySimpleBlockContentValue
  | InternationalizedArrayStringValue
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug
